"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r9q5x97z#5^%4^01+xk5w6!eyu6i$86y9mm3=7zx34@)v3nzce'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['192.168.1.4','*']
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'qr_code',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'import_export',
    'ekspedisi',
    'kurir'
]

INTERNAL_IPS = [
    "127.0.0.1",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'ekspedisi.User'
AUTHENTICATION_BACKENDS = ['ekspedisi.custom_backend.UserEmailBackend']

ROOT_URLCONF = 'project.urls'

SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(SETTINGS_PATH, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'ekspedisi.context_processors.api_maps_view',
                'ekspedisi.context_processors.api_open_route_service',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases`

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'db_baligo',
        # 'USER': 'samitra',
        # 'PASSWORD': 'Ekspedisi@samitra2021',
        # 'HOST': 'localhost',   # Or an IP Address that your DB is hosted on

        'USER': 'root',
        'PASSWORD': '',
        # 'PASSWORD': 'bizdev@2024',
        'HOST': 'localhost',   # Or an IP Address that your DB is hosted on

        'PORT': '3306',
        'OPTIONS': {
            'sql_mode':'traditional',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'ekspedisi/static/')
MEDIA_ROOT = os.path.join(BASE_DIR,'ekspedisi/media/')

LOGIN_URL = '/'
LOGOUT_URL = '/'

IMPORT_EXPORT_USE_TRANSACTIONS = True

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'qr-code': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qr-code-cache',
        'TIMEOUT': 3600
    }
}

QR_CODE_CACHE_ALIAS = 'qr-code'
MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

# Email settings
# EMAIL_HOST = 'smtp.mailtrap.io'
# EMAIL_HOST_USER = '5b71992f271e46'
# EMAIL_HOST_PASSWORD = '5cca2c8287facc'
# EMAIL_PORT = '2525'
# 

# MAIL_DRIVER=smtp
# MAIL_HOST=smtp-relay.sendinblue.com
# MAIL_PORT=587
# MAIL_USERNAME=bithousebali@gmail.com
# MAIL_PASSWORD=1swD56facXZAFIgV
# MAIL_ENCRYPTION=null
# MAIL_FROM_ADDRESS=paketmu@bithouse.id
# MAIL_FROM_NAME=PaketKamu

EMAIL_HOST = 'smtp-relay.sendinblue.com'
EMAIL_HOST_USER = 'bithousebali@gmail.com'
EMAIL_HOST_PASSWORD = '1swD56facXZAFIgV'
EMAIL_PORT = '587'


API_MAPS_VIEW = 'pk.eyJ1IjoiYmhhcnUiLCJhIjoiY2l0dmhxYWcwMDA1cjJ6cW14eHVpaHp4eCJ9.atVtH1bNhN4WgYUrzh0h_g'
API_OPEN_ROUTE_SERVICE = '5b3ce3597851110001cf62486f09c07e222343b09d62cf8daadf701d'

CORS_ORIGIN_ALLOW_ALL = True
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-CSRF-TOKEN',
]

env = environ.Env()
environ.Env.read_env()
OAUTH_PROVIDER_URL = env('OAUTH_PROVIDER_URL')
OAUTH_CLIENT_ID = env('OAUTH_CLIENT_ID')
OAUTH_CLIENT_SECRET = env('OAUTH_CLIENT_SECRET')
OAUTH_REDIRECT_URI = env('OAUTH_REDIRECT_URI')

# Session engine (make sure this is correctly set up)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Store sessions in the database

# Set session cookie settings (optional, but ensure no conflicts)
SESSION_COOKIE_NAME = 'sessionid'
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout