version: "3.9"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'ekspedisi'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./data/mysql/db:/var/lib/mysql

  phpMyAdmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    ports:
      - "8080:80"

  app:
    build: .
    volumes:
      - .:/django-ekspedisi
    ports:
      - "8000:8000"
    container_name: django_ekspedisi_container
    command: python project/manage.py runserver 0.0.0.0:8000 
    depends_on:
      - db

volumes:
  db:
    driver: local