from .login_register import *
from .pengemasan import *
from .kendaraan import *
from .kurir import *
from .order_pickup import *
from .kontak import *
from .tentang import *
from .gudang import *
from .toko import *
from .pelanggan import *
from .personil import *
from .dashboard import *
from .tarif_gudang import *
from .tarif_kilometer import *
from .tarif_berat import *
from .layanan import *
from .tarif_layanan import *
from .pengiriman import *
from .lokasi_options import *
from .maps_api import *
from .log_pengiriman import *
from .TokoAPIView import *
from .GudangAPIView import *
from .PengemasanAPIView import *
from .LokasiAPIView import *
from .LayananAPIView import *
from .pesan_pelanggan import *
from .profile import *
from .extra_cash import *
from .satuan import *
from .order_pickup_outlet import *
from .PengirimanAPIView import *
from .OrderPickupAPIView import *
from .SatuanAPIView import *
from .JenisKirimanAPIView import *
from .PelangganTrackAPIView import *
from .jenis_kiriman import *