from .auth import *
from .home import *
from .register import *
from .tentang import *
from .kontak import *
from .tarif import *
from .track import *
from .order import *
from .profile import *
from .api_lokasi import *